---
title: "Workbook to investigate Question 2"
author: "Luciana Mazili & Rohin Chhabra"
date: "10/09/2020"
output: 
  html_document:
     number_sections: no
     fig_caption: yes
     toc: true
     toc_depth: 2
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(tidyverse)
library(sqldf)
library(ggplot2)
library(RColorBrewer)

```

```{r loading the data frame (df)}
#loading the data frame (df)
crashDF <- read_rds("../datasets/main.Rds")

```



# Question 2 - Is higher average monthly rainfall related to an increase in fatalities?


```{r fatality sum by year}
# fatality sum by year
Year_Fatality = sqldf("SELECT SUM(Count_Casualty_Fatality) as Fatality, Crash_Year FROM crashDF GROUP BY Crash_Year")
```

```{r accidents sum excluding by year & rainfall}
Year_Accidents_Rainfall = sqldf(("SELECT COUNT(crash_id) as Accident, Crash_Year FROM crashDF GROUP BY Crash_Year"))
```

```{r fatality sum by year, month}
# fatality sum by year, month
month_Fatality = sqldf("SELECT SUM(Count_Casualty_Fatality) as Fatality, Crash_Year, Crash_Month, SUM(rainfall) as total_rainfall FROM crashDF GROUP BY Crash_Year, Crash_Month")

month_Fatality['avg_rainfall'] <- NA
month_Fatality$avg_rainfall <- month_Fatality$total_rainfall/30.42

month_Fatality$Crash_Month = factor(month_Fatality$Crash_Month, levels = month.name)
```


```{r}
ggplot(Year_Accidents_Rainfall, aes(x=Crash_Year, y=Accident)) +
  geom_point() +
  geom_smooth() +
  scale_x_continuous(breaks=c(2001:2018), labels=c(2001:2018)) +
  labs(x = "Year", y= "Accident", title = "Number of Motorcycle Accidents by Year") +
  theme_bw()

```



```{r plot fatality sum by year, message=FALSE}
# plot fatality sum by year
ggplot(Year_Fatality, aes(x=Crash_Year, y=Fatality)) +
  geom_point() +
  geom_smooth() +
  scale_x_continuous(breaks=c(2001:2018), labels=c(2001:2018)) +
  labs(x = "Year", y= "Fatality", title = "Number of Motorcycle Fatalities by Year") +
  theme_bw()

```


```{r fatality sum by month & AVG rainfall}
#fatality sum by month & rainfall AVG
Month_fatality_Rainfall = sqldf("SELECT SUM(Fatality) as Fatality, Crash_Month, avg_rainfall FROM month_Fatality GROUP BY Crash_Month") 
```


```{r  Accident sum by month & rainfall}
#ggplot() + 
#  geom_bar(Month_fatality_Rainfall,aes(x = Crash_Month,Y = value,fill = variable), stat = "identity", #position = "identity") + geom_line(Month_fatality_Rainfall,aes(Crash_Month, avg_rainfall))

ggplot(data=Month_fatality_Rainfall, aes(x=Crash_Month, y=Fatality, fill=avg_rainfall)) +
    geom_bar(colour="black", stat="identity") +
      scale_x_discrete(limits = month.name) +
      labs(x = "Month", y = "Fatality", fill =  "Rainfall", title = "Number of Motorcycle Fatality by Month from 2001 to 2018") +
    theme_bw() +
       theme(plot.title = element_text(size = 12, face = "bold", hjust = 0.5),
              text = element_text(size = 9),
              axis.title = element_text(face="bold"),
              axis.text.x=element_text(size = 11, angle = 90, vjust = 0.5, hjust=1),
              legend.position = "right") +
              scale_fill_continuous(trans = 'reverse')
              #scale_fill_continuous(high = "#132B43", low = "#56B1F7")
              # scale_color_hue(direction = -1)
                

```

```{r}
ggplot(Month_fatality_Rainfall, aes(x=Crash_Month, y=Fatality, colour=avg_rainfall)) +
 geom_point() +
 scale_x_discrete(limits = month.name) +
  labs(x = "Month", y= "Fatality", title = "Number of Motorcycle Fatality by Month from 2001 to 2018")
```


```{r plot by year & month & rainfall}
library(ggplot2)
ggplot(month_Fatality, aes(x=Crash_Month, y=Fatality, colour=avg_rainfall)) +
  facet_wrap(~Crash_Year) +
  geom_point() +
    scale_x_discrete(limits = month.name) +
    labs(x = "Month", y= "Fatality", title = "Number of Motorcycle fatality & rainfall per month by Year") +
    theme_bw()

```



```{r fatality sum by month, eval=FALSE, include=FALSE}
# Month_Fatality = sqldf("SELECT SUM(Count_Casualty_Fatality) as Fatality, Crash_Month FROM main GROUP BY Crash_Month")
```


```{r fatality sum by month & rainfall}
#fatality sum by month & rainfall AVG
#Month_fatality_Rainfall = sqldf("SELECT SUM(Count_Casualty_Fatality) as Fatality, Crash_Month, rainfall FROM crashDF GROUP BY Crash_Month") 
```


```
#no rainfall
box1 <- ggplot(month_Fatality, aes(x=Crash_Month, y=Fatality, fill=rainfall)) +
  geom_boxplot(fill = fill, colour = line)+
  scale_x_discrete(name = 'Month')+
  scale_y_continuous(name = "Number of Fatalities", breaks = seq(0, 12, 2))+
  ggtitle("Boxplot of total fatalities by month")+
  theme_bw() +
        theme(plot.title = element_text(size = 14, family = "Tahoma", face = "bold"),
              text = element_text(size = 12, family = "Tahoma"),
              axis.title = element_text(face="bold"),
              axis.text.x=element_text(size = 11, angle = 90, vjust = 0.5, hjust=1),
              legend.position = "bottom")+
   scale_fill_brewer(palette = "Accent") +
        labs(fill = "Rainfall")
  #+facet_grid(. ~ rainfall)

box1
```
mean(month_Fatality$avg_rainfall)

```{r plot fatality sum by month & rainfall}
#plot fatality sum by month & rainfall

month_Fatality$avg_rainfall <- factor(ifelse(month_Fatality$avg_rainfall > mean(month_Fatality$avg_rainfall), 1, 0),
                                    labels = c("Below average", "Above average"))

box <- ggplot(month_Fatality, aes(x=Crash_Month, y=Fatality, fill=avg_rainfall)) +
  geom_boxplot(alpha=5)+
  scale_x_discrete(name = 'Month')+
  scale_y_continuous(name = "no. of fatalities", breaks = seq(0, 12, 2))+
  ggtitle( "Fatalities vs Rainfall (monthly averages)", subtitle = "(2001-2008)" )+
  theme_bw() +
        theme(
              axis.text.x=element_text(angle = 45, hjust=1),
              legend.position = "right")+
              scale_fill_manual(values = c("#FFDDDD","#CCEEFF")) +
        labs(fill = "Rainfall")
  #+facet_grid(. ~ rainfall)

box
```


```{r fatality sum by year, month, Total & AvG Rainfall}

# fatality sum by year, month
month_Fatality_cut = sqldf("SELECT SUM(Count_Casualty_Fatality) as Fatality, Crash_Year, Crash_Month, SUM(rainfall) as total_rainfall FROM crashDF GROUP BY Crash_Year, Crash_Month")

month_Fatality_cut['avg_rainfall'] <- NA
month_Fatality_cut$avg_rainfall <- month_Fatality_cut$total_rainfall/30.42

month_Fatality_cut$Crash_Month = factor(month_Fatality_cut$Crash_Month, levels = month.name)

month_Fatality_cut[['rainfall_range']] <- cut(month_Fatality_cut$avg_rainfall, c(0, 4, 16, 32, 64), right=FALSE)

summedFatalities <- aggregate(Fatality ~ rainfall_range, month_Fatality_cut, FUN = sum)

barSum <- ggplot(data=summedFatalities, aes(x=rainfall_range, y=Fatality, fill=rainfall_range)) +
  ggtitle("Total fatalities vs average monthly rainfall")+
  geom_bar(stat="identity", width=0.5)+
  geom_text(aes(label = Fatality), hjust = 0.5, position=position_dodge(1), size=3.5) +

  #scale from: https://www.sciencedirect.com/science/article/pii/S1877705816333124  
  scale_x_discrete(name = element_blank(), labels = element_blank())+
  scale_y_continuous(name = "Number of Fatalities", breaks = seq(0, 500, 50))+
theme_bw()+
  theme(plot.title = element_text(size = 12, hjust = 0.5),
              text = element_text(size = 9),
              axis.text.x=element_text(size = 11, angle = 90, vjust = 0.5, hjust=1),
              legend.position = "left")+
  scale_fill_discrete(name = "Average Rainfall Range", labels = c("Light: 0-4mm/day", "Light-Moderate: 4-16mm/day", "Moderate-Heavy: 16-32mm/day", "Heavy: 32-64mm/day"))

barSum

```



```{r plot rainfall & Count_Casualty_Fatality}
ggplot(crashDF, aes(x=rainfall, y=Count_Casualty_Fatality))  +
  geom_point()
```
```{R}
cor(crashDF$rainfall,crashDF$Count_Casualty_Fatality)
```
#  slm 

```{R}
slm <- lm(Count_Casualty_Fatality~rainfall,data=crashDF)
```

```{r}
coef(slm)
```


```{r}
ggplot(data=crashDF, aes(x=rainfall,y=Count_Casualty_Fatality)) + geom_point()+ 
  geom_smooth(method='lm')
```



```{r}
summary(slm)
```















